figure
plot3(experiments{1,1}(1,8),experiments{1,1}(1,9),experiments{1,1}(1,10),'*')
hold on;
% for i=1:1000:length(experiments{1,1})
%     figure(i)
    quat = [experiments{1,1}(1,17), experiments{1,1}(1,14), experiments{1,1}(1,15), experiments{1,1}(i,16)];
       eulZYX = quat2eul(quat);
    h = triad('Parent',axes,'Scale',1,'LineWidth',3,...
           'Tag','Triad Example','Matrix',...
           makehgtform('xrotate',eulZYX(3),...
                       'yrotate',eulZYX(2),...
                       'zrotate',eulZYX(1),...
                       'translate',[experiments{1,1}(1,11),...
                                    experiments{1,1}(1,12),...
                                    experiments{1,1}(1,13)]));
   H = get(h,'Matrix');
   for i=1:length(experiments{1,1})
       quat = [experiments{1,1}(i,17), experiments{1,1}(i,14), experiments{1,1}(i,15), experiments{1,1}(i,16)];
       eulZYX = quat2eul(quat);
          set(h,'Matrix',H*makehgtform('xrotate',eulZYX(3),...
                       'yrotate',eulZYX(2),...
                       'zrotate',eulZYX(1),...
                       'translate',[experiments{1,1}(i,11),...
                                    experiments{1,1}(i,12),...
                                    experiments{1,1}(i,13)]));
          drawnow
   end
% end